// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MvcZoo.Data;
using System;

namespace MvcZoo.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20180320092901_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcZoo.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MyCageId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MyCageId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("MvcZoo.Models.Cage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Cages");
                });

            modelBuilder.Entity("MvcZoo.Models.Animal", b =>
                {
                    b.HasOne("MvcZoo.Models.Cage", "MyCage")
                        .WithMany("Animals")
                        .HasForeignKey("MyCageId");
                });
#pragma warning restore 612, 618
        }
    }
}
